### ISSUE TITLE
Create GSA DS 

### ISSUE THREAD

**Issue by jcastle-zz** [GSA/GSADigitalService#1]
Create a GSA DS site as the template site for future site creations.  Standardize on one Jekyll template that incorporates USWDS standards.
- [ ] determine Jekyll template
- [ ] incorporate USWDS standards
- [ ] use site to store docs for GSA DS team and others to use
- [ ] use site as the one place to have a public face
- [ ] similar to cto.gsa.gov but for GSA DS specific content

**Comment by jfredrickson5** [comment]
Stuff we should clarify regarding the template:

Is the intent of this template to have one look-and-feel for all sites we produce? Or is it to just provide a project structure that contains the USWDS files so that we don't have to bootstrap a new project structure every time we create a site?

Is this a template for all websites we create (including web apps) or just static/Jekyll sites?
